### ISSUE TITLE
Conventions: Symbol pin order

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/librepcb-doc#17]
When designing symbols (e.g. for the [Blue Pill](http://wiki.stm32duino.com/images/a/ae/Bluepillpinout.gif)), how should the pins be sorted?

Some ways that come to mind:

- All on one side, sorted numerically
- On both sides, sorted numerically counterclockwise
- Matching the physical design
- Sorted logically (e.g. a group with I/O pins, all GND pins at the bottom, all power pins at the top, etc)

Any suggestions?

**Comment by dbrgn** [comment]
Given that @ubruhin wrote:

> A schematic is a logical representation of a circuit, not mechanical. So even if the footprint has two GND pins, if they are electrically connected, one GND pin in schematics is enough.

(See https://github.com/LibrePCB/LibrePCB/issues/288)

...I think matching the phyical layout does not really make sense.

Here's one suggestion for the [blue pill symbol](http://wiki.stm32duino.com/images/a/ae/Bluepillpinout.gif):

![img](https://tmp.dbrgn.ch/screenshots/20180718174939-0xebtdx0.png)

**Comment by ubruhin** [comment]
As there are many different opinions, and the fact that a Component can have different symbol variants, I would say the goal should be to support four different symbol variants:

1. Sorted logically (I would set this as the default symbol variant)
   - Advantage: Schematics are easily readable because they represent the *logic* of the circuit
2. On both sides, sorted numerically counterclockwise
   - Advantage: Can be solved using very generic symbols. Only one symbol per pin count is required (e.g. "IC with 10 Pins", "IC with 12 Pins", "IC with 14 Pins", ...)
3. Splitted logically (one dedicated symbol for each logical part of the component)
   - Advantage: Especially useful for very large components (>100 Pins) to keep schematics readable
4. Matching the physical design

As we can add more symbol variants step by step, I would suggest to just add the logical sorted symbol for the moment.

Btw, I would not place pins at the top or bottom. IMHO they make schematics less readable.

**Comment by alexforencich** [comment]
I think only 1 symbol variant (sorted logically) is the best approach.  I honestly don't see any good reason for any component to have more than 1 symbol variant.  It's just going to make libraries hard to maintain if there are multiple symbol variants for each part that have to be kept in sync.  Things like op amps, logic gates, and high pin count parts (hundreds or thousands of pins) would use sub-symbols that could even be placed on separate schematic sheets.  Generic symbols are unnecessary for ICs because you need a specific symbol for each part anyway, though I can see putting in a button to auto-generate a configurable number of pins that can then be named, moved, etc.  

As for pin locations...avoid the top and bottom edges.  This will waste space within the symbol to prevent the pin names from overlapping.  Parts like voltage regulators may be an exception to that.

**Comment by rnestler** [comment]
I think this can be closed, since we strongly agree that symbols should be sorted logically and it is also mentioned in the [Symbol Conventions](https://docs.librepcb.org/#libraryconventions-symbols).
Any objections?

**Comment by dbrgn** [comment]
I agree.
