### ISSUE TITLE
Conventions: Silkscreen Outline

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/librepcb-doc#3]
When designing footprints, e.g. for an SOT-23-5:

![sot235](https://tmp.dbrgn.ch/screenshots/20180404213840-lgs_wybv.png)

...should we (1) include the outline of the plastic case in the footprint?

According to @ubruhin, "the solder mask is automatically subtracted from silkscreen to avoid silkscreen on copper", so this would work.

![overlapping](https://tmp.dbrgn.ch/screenshots/20180404214151-9i3vq75z.png)

Or should we (2) make the rectangle smaller to avoid the pads?

![smaller](https://tmp.dbrgn.ch/screenshots/20180404214048-xse_p1xt.png)

Or should we (3) work with lines?

![lines](https://tmp.dbrgn.ch/screenshots/20180404214716-6d1qlx7v.png)

**Comment by dbrgn** [comment]
I tend to favor (1) because it looks best in my eyes, as long as silkscreen - copper is not a problem. Additionally, it can give an idea of the actual outline of the package.

If the datasheet includes tolerance (min / nominal / max), the max value should be used.

**Comment by hephaisto** [comment]
@dbrgn Shouldn't packages be more general and not depend on a probably part/vendor-specific datasheet?
I would favor (1) - or rather have it exactly the same size as the plastic package.

**Comment by ubruhin** [comment]
> According to @ubruhin, "the solder mask is automatically subtracted from silkscreen to avoid silkscreen on copper", so this would work.

Yeah that's currently the case, but I'm not sure if we can rely on that because later it might be configurable whether the solder mask should be subtracted from silkscreen or not. In addition, there might be a check in the DRC which raise warnings if silkscreen overlaps with copper.

So probably it would be better to avoid that overlap in footprints, even if currently it's not a problem.

I think it would be best to distinguish between layers which are used for solder mask, and layers which are documentation-only. Then solder mask layers must not overlap with copper, while the documentation layers are allowed to overlap.

**Comment by dbrgn** [comment]
> So probably it would be better to avoid that overlap in footprints, even if currently it's not a problem.

Maybe the part editor could help with that, by providing boolean operations ("subtract copper layer from placement layer"). That would make non-overlapping design simpler, you could simply draw a rectangle and then subtract the copper.

> Shouldn't packages be more general and not depend on a probably part/vendor-specific datasheet?

Hm, that's a good point - how do we deal with tolerances? What if a vendor has slightly incompatible parts and/or different tolerance recommendations, should we create device-specific variations?

Or should we simply create vendor specific versions like "Microchip SOT-23-5" and "TI SOT-23-5" even if they may be identical?

**Comment by ubruhin** [comment]
@dbrgn I would say this topic is now pretty good documented in the current library conventions, so can we close this issue?

**Comment by dbrgn** [comment]
Yep, you're right!
